import { ReactNode } from 'react'
import './globals.css'
import { Rajdhani } from 'next/font/google'

const rajdhani = Rajdhani({
  subsets: ['latin'],
  weight: '500',
  variable: '--font-rajdhani',
})

export const metadata = {
  title: 'Matheus Pinheiro',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }: { children: ReactNode }) {
  return (
    <html lang="en">
      <body className={`${rajdhani.className} bg-gray-500`}>{children}</body>
    </html>
  )
}
